# Generated by Django 2.0.7 on 2018-07-17 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.FileField(max_length=200, upload_to='')),
                ('section', models.FileField(max_length=200, upload_to='')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2018, 7, 17, 15, 31, 40, 471739, tzinfo=utc))),
            ],
        ),
    ]
