# Generated by Django 2.0.7 on 2018-07-17 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 15, 32, 38, 93961, tzinfo=utc)),
        ),
    ]
