# Generated by Django 2.0.7 on 2018-07-17 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0002_auto_20180717_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='section',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 15, 54, 32, 198267, tzinfo=utc)),
        ),
    ]
