# Generated by Django 2.0.7 on 2018-07-19 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0005_auto_20180718_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='file',
            field=models.FileField(default='BLANK TEXT', upload_to=''),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 20, 49, 18, 221612, tzinfo=utc)),
        ),
    ]
