# Generated by Django 2.0.7 on 2018-07-19 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0006_auto_20180719_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 20, 49, 40, 639355, tzinfo=utc)),
        ),
    ]
