# Generated by Django 2.0.7 on 2018-07-21 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0007_auto_20180719_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='status',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 3, 14, 9, 523999, tzinfo=utc)),
        ),
    ]
