# Generated by Django 2.0.7 on 2018-07-21 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0008_auto_20180721_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 4, 8, 14, 867817, tzinfo=utc)),
        ),
    ]
