# Generated by Django 2.0.7 on 2018-07-22 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0009_auto_20180721_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='available',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 11, 35, 45, 81292, tzinfo=utc)),
        ),
    ]
