# Generated by Django 2.0.7 on 2018-07-22 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0010_auto_20180722_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 13, 52, 54, 192995, tzinfo=utc)),
        ),
    ]
