# Generated by Django 2.0.7 on 2018-07-23 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0011_auto_20180722_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 18, 35, 41, 523606, tzinfo=utc)),
        ),
    ]
