# Generated by Django 2.0.7 on 2018-07-24 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0015_auto_20180723_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='available',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='section',
            field=models.CharField(default='00', max_length=200),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='status',
            field=models.BooleanField(default='Flase'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 15, 57, 21, 653598, tzinfo=utc)),
        ),
    ]
