# Generated by Django 2.0.7 on 2018-07-24 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_book', '0016_auto_20180724_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 15, 59, 1, 250178, tzinfo=utc)),
        ),
    ]
